project:
  type: website

website:
  title: "Fidèle Balume"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Research.qmd
      - links.qmd
      - posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

